name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

      - name: Install Yarn
        run: npm install -g yarn

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 65002
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html && git pull
            cd wp-content/themes/videography
            composer install
            yarn
            yarn build
